(ns typing-monkeys.style.constants)

(def css-keys
  [:-fx-alignment
   :-fx-alternative-column-fill-visible
   :-fx-alternative-row-fill-visible
   :-fx-animated
   :-fx-arc-height
   :-fx-arc-width
   :-fx-arrows-visible
   :-fx-background-color
   :-fx-background-fills
   :-fx-background-image
   :-fx-background-images
   :-fx-background-insets
   :-fx-background-position
   :-fx-background-radius
   :-fx-background-repeat
   :-fx-background-size
   :-fx-bar-gap
   :-fx-blend-mode
   :-fx-block-increment
   :-fx-border-color
   :-fx-border-image-insets
   :-fx-border-image-repeat
   :-fx-border-image-slice
   :-fx-border-image-source
   :-fx-border-image-width
   :-fx-border-insets
   :-fx-border-radius
   :-fx-border-style
   :-fx-border-width
   :-fx-category-gap
   :-fx-cell-size
   :-fx-clockwise
   :-fx-collapsible
   :-fx-color-label-visible
   :-fx-column-halignment
   :-fx-content-display
   :-fx-context-menu-enabled
   :-fx-create-symbols
   :-fx-cursor
   :-fx-display-caret
   :-fx-effect
   :-fx-ellipsis-string
   :-fx-end-margin
   :-fx-fill
   :-fx-fill-height
   :-fx-fill-width
   :-fx-fit-to-height
   :-fx-fit-to-width
   :-fx-focus-traversable
   :-fx-font
   :-fx-font-family
   :-fx-font-scale
   :-fx-font-size
   :-fx-font-smoothing-type
   :-fx-font-style
   :-fx-font-weight
   :-fx-gap-start-and-end
   :-fx-graphic
   :-fx-graphic-text-gap
   :-fx-grid-lines-visible
   :-fx-halignment
   :-fx-hbar-policy
   :-fx-hgap
   :-fx-highlight-fill
   :-fx-highlight-text-fill
   :-fx-horizontal-grid-lines-visible
   :-fx-horizontal-zero-line-visible
   :-fx-image
   :-fx-image-borders
   :-fx-indent
   :-fx-indeterminate-bar-animation-time
   :-fx-indeterminate-bar-escape
   :-fx-indeterminate-bar-flip
   :-fx-indeterminate-bar-length
   :-fx-label-line-length
   :-fx-label-padding
   :-fx-legend-side
   :-fx-legend-visible
   :-fx-major-tick-unit
   :-fx-max-height
   :-fx-max-page-indicator-count
   :-fx-max-width
   :-fx-min-height
   :-fx-min-width
   :-fx-minor-tick-count
   :-fx-minor-tick-length
   :-fx-minor-tick-visible
   :-fx-opacity
   :-fx-orientation
   :-fx-padding
   :-fx-page-information-alignment
   :-fx-page-information-visible
   :-fx-pannable
   :-fx-pie-label-visible
   :-fx-position-shape
   :-fx-pref-columns
   :-fx-pref-height
   :-fx-pref-rows
   :-fx-pref-tile-height
   :-fx-pref-tile-width
   :-fx-pref-width
   :-fx-progress-color
   :-fx-prompt-text-fill
   :-fx-rotate
   :-fx-row-valignment
   :-fx-scale-shape
   :-fx-scale-x
   :-fx-scale-y
   :-fx-scale-z
   :-fx-shape
   :-fx-show-tick-labels
   :-fx-show-tick-marks
   :-fx-side
   :-fx-size
   :-fx-skin
   :-fx-smooth
   :-fx-snap-to-pixel
   :-fx-snap-to-ticks
   :-fx-spacing
   :-fx-start-angle
   :-fx-start-margin
   :-fx-strikethrough
   :-fx-stroke
   :-fx-stroke-borders
   :-fx-stroke-dash-array
   :-fx-stroke-dash-offset
   :-fx-stroke-line-cap
   :-fx-stroke-line-join
   :-fx-stroke-miter-limit
   :-fx-stroke-type
   :-fx-stroke-width
   :-fx-tab-max-height
   :-fx-tab-max-width
   :-fx-tab-min-height
   :-fx-tab-min-width
   :-fx-text-alignment
   :-fx-text-fill
   :-fx-text-origin
   :-fx-text-overrun
   :-fx-tick-label-fill
   :-fx-tick-label-font
   :-fx-tick-label-gap
   :-fx-tick-labels-visible
   :-fx-tick-length
   :-fx-tick-mark-visible
   :-fx-tick-unit
   :-fx-tile-alignment
   :-fx-title-side
   :-fx-tooltip-visible
   :-fx-translate-x
   :-fx-translate-y
   :-fx-translate-z
   :-fx-underline
   :-fx-unit-increment
   :-fx-use-system-menu-bar
   :-fx-valignment
   :-fx-vbar-policy
   :-fx-vertical-grid-lines-visible
   :-fx-vertical-zero-line-visible
   :-fx-vgap
   :-fx-wrap-text])

(def colors
  [:aliceblue
   :antiquewhite
   :aqua
   :aquamarine
   :azure
   :beige
   :bisque
   :black
   :blanchedalmond
   :blue
   :blueviolet
   :brown
   :burlywood
   :cadetblue
   :chartreuse
   :chocolate
   :coral
   :cornflowerblue
   :cornsilk
   :crimson
   :cyan
   :darkblue
   :darkcyan
   :darkgoldenrod
   :darkgray
   :darkgreen
   :darkgrey
   :darkkhaki
   :darkmagenta
   :darkolivegreen
   :darkorange
   :darkorchid
   :darkred
   :darksalmon
   :darkseagreen
   :darkslateblue
   :darkslategray
   :darkslategrey
   :darkturquoise
   :darkviolet
   :deeppink
   :deepskyblue
   :dimgray
   :dimgrey
   :dodgerblue
   :firebrick
   :floralwhite
   :forestgreen
   :fuchsia
   :gainsboro
   :ghostwhite
   :gold
   :goldenrod
   :gray
   :green
   :greenyellow
   :grey
   :honeydew
   :hotpink
   :indianred
   :indigo
   :ivory
   :khaki
   :lavender
   :lavenderblush
   :lawngreen
   :lemonchiffon
   :lightblue
   :lightcoral
   :lightcyan
   :lightgoldenrodyellow
   :lightgray
   :lightgreen
   :lightgrey
   :lightpink
   :lightsalmon
   :lightseagreen
   :lightskyblue
   :lightslategray
   :lightslategrey
   :lightsteelblue
   :lightyellow
   :lime
   :limegreen
   :linen
   :magenta
   :maroon
   :mediumaquamarine
   :mediumblue
   :mediumorchid
   :mediumpurple
   :mediumseagreen
   :mediumslateblue
   :mediumspringgreen
   :mediumturquoise
   :mediumvioletred
   :midnightblue
   :mintcream
   :mistyrose
   :moccasin
   :navajowhite
   :navy
   :oldlace
   :olive
   :olivedrab
   :orange
   :orangered
   :orchid
   :palegoldenrod
   :palegreen
   :paleturquoise
   :palevioletred
   :papayawhip
   :peachpuff
   :peru
   :pink
   :plum
   :powderblue
   :purple
   :red
   :rosybrown
   :royalblue
   :saddlebrown
   :salmon
   :sandybrown
   :seagreen
   :seashell
   :sienna
   :silver
   :skyblue
   :slateblue
   :slategray
   :slategrey
   :snow
   :springgreen
   :steelblue
   :tan
   :teal
   :thistle
   :tomato
   :turquoise
   :violet
   :wheat
   :white
   :whitesmoke
   :yellow
   :yellowgreen
   :transparent])